### ISSUE TITLE
Rare Crash on Launch

### ISSUE THREAD

**Issue by Siri-chan** [Siri-chan/io.siri.joe#1]
## Description
A crash that can occur at game startup, no video beforehand, havent experimented enough to find a concrete cause.
## Stack Trace
```sh
Exception in thread "Thread-0" java.util.ConcurrentModificationException
	at java.base/java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970)
	at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:892)
	at io.siri.joe.Handler.render(Handler.java:25)
	at io.siri.joe.Core.render(Core.java:108)
	at io.siri.joe.Core.run(Core.java:74)
	at java.base/java.lang.Thread.run(Thread.java:831)
```
## How to Replicate
I have no idea what's happening to trigger this.
## Additional Ponderings/Comments
My best guess is it's the render method being called before gameobjects finish initialising.
Or perhaps pressing keys before gameobjects start to initialise, but I am unsure.

**Comment by Siri-chan** [comment]
This is definitely related to adding gameobjects after JOE starts. I should probably write a locking system for addign GameObjects during play.
For now I have written a fix to separate the `start()` method from the `init()`, which means that the crash should no longer happen on launch, but this can still happen at any time if adding components at runtime.

**Comment by Siri-chan** [comment]
fixed in 0.6.1
